services:
  mysql-db: # nome do servico
    image: mysql #caminho da imagem no dockerHub
    container_name: ger-library-mysql #nome do container
    environment: #variaveis de ambiente
      MYSQL_ROOT_PASSWORD: root #senha
    ports: 
      - 3307:3306 # Porta do Host : Porta do container. essa especificacao faz o espelhamento do container no host
    networks:
      - ger-network
    restart: always
      
  app:
    image: ronaldliboni/ger-library:1.0
    container_name: ger-library
    depends_on: # so iniciar quando terminar de criar o mySql-db. OBS importante: o DB estar criado, não significa que está pronto para receber conexões
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/gers-library-api?createDatabaseIfNotExist=TRUE
    ports:
     - 9090:8080  # host:container
    networks:
      - ger-network
    restart: on-failure
        
networks:
  ger-network:
    driver: bridge
    
